version: '3.9'

services:

    torivahti:
      image: python:3.6.7-slim
      volumes:
        - ./torivahti.py:/usr/src/torivahti.py
      tty: true
      command: python -u /usr/src/torivahti.py 10 120

