version: '3.9'

services:

    frontend:
      image: ml-frontend:latest
      ports:
        - 3000:5000
      networks:
        mlnet:
          ipv4_address: 172.18.0.2
      command: serve -s -l 3000 build

    backend:
      image: ml-backend:latest
      ports:
        - 5000:3000
      networks:
        mlnet:
          ipv4_address: 172.18.0.3
      volumes:
        - model:/src/model
      command: python -u app.py
      
    training:
      image: ml-training:latest
      volumes:
        - model:/src/model
        - training:/src/training
      command: python -u train.py
      
networks:
  mlnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1

volumes:
  model:
  training:
